#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 27 08:50:47 2021

@author: ji-chingchen
"""
import numpy as np
# import matplotlib
# matplotlib.use('TkAgg') 
from matplotlib import cm
import matplotlib.pyplot as plt
magma=1e-14
dt=2
lam0 = 1e-12
# lam0 = np.logspace(-10,-15)
lam_tdep = 8e-3
lam_tdep = np.logspace(-2,-8,10)
delT=600-10

# print(lam_tdep,lam)

fig, (ax)= plt.subplots(1,1,figsize=(12,8))

def lam(lam0,lam_tdep):
    lam = lam0*(1+np.exp(-lam_tdep*delT))
    return lam
def magma_all(dt,prod,magma,lam):
    total_magma=prod * dt - magma * np.exp(-lam * dt)
    return total_magma

rainbow = cm.get_cmap('rainbow',10)
color_list = rainbow(np.linspace(0.2,1,10))
range_lam0 = np.logspace(-10,-14,10)
for kk,lam0 in enumerate (range_lam0):
    for lam_ttdep in lam_tdep:
        llt = lam(lam0,lam_ttdep)
        ax.scatter(lam_ttdep,llt,c=color_list[kk],label=str(lam0))
ax.set_xscale("log")
# ax.set_yscale("log")
